### ISSUE TITLE
Tab margin separator doesn't change with margin color

### ISSUE THREAD

**Issue by zakissimo** [AlphaTechnolog/pywal.nvim#2]
I would like to change the color of the seperations between my tabs in lualine (here in white) and either have them sync with the margin color and size, or at least, make them blend in with lualine background color.

![2022-02-04-132402_1268x58_scrot](https://user-images.githubusercontent.com/64891486/152528815-d9c1ef8f-18cd-4b16-ba27-3de744b37b0d.png)

The reason I'm posting here and not on lualine's github is because I don't see this problem with other color schemes.

My config file:
`
local pywal = require('pywal')

pywal.setup()
`

**Comment by AlphaTechnolog** [comment]
Really, I do not know why that white appears there, maybe I happened to put the color of the background or in your case the blue in the lualine theme. Although a possible solution is to put a light color that synchronizes with the white color so that it is not so ugly

**Comment by AlphaTechnolog** [comment]
This is a test, the lualine with a light color in normal mode:

![Screenshot from 2022-02-08 11-29-42](https://user-images.githubusercontent.com/54639968/153019876-0070021c-9ea1-42d8-9a0b-d7291bc96907.png)

![Screenshot from 2022-02-08 11-30-40](https://user-images.githubusercontent.com/54639968/153019982-8acf8cd2-4f77-4b20-92e9-57e1d1253f9b.png)

This is an experimental fix, I will search what is going on with it white color

**Comment by AlphaTechnolog** [comment]
I found the problem, the problem is I miss this highlights in the config of the colorscheme:

- StatusLine
- StatusLineNC

If I set `guibg` to `colors.background` and `guifg` to `colors.background` in it's highlights, the problem is solved

![Screenshot from 2022-02-08 11-47-33](https://user-images.githubusercontent.com/54639968/153023483-30140718-af36-4162-be56-c5270cc59892.png)

I will push this fix to the main branch, update the plugin :D

**Comment by AlphaTechnolog** [comment]
I close ithis issue because the problem is solved for me
If you have any problem, reopen the issue :)
