### ISSUE TITLE
Highlight current line

### ISSUE THREAD

**Issue by ivan-volnov** [AlphaTechnolog/pywal.nvim#9]
Hello,

Thank you for the plugin!

How to highlight current line?

**Comment by AlphaTechnolog** [comment]
try using `vim.opt.cursorline = true` or with vim script `set cursorline`

**Comment by ivan-volnov** [comment]
I have `set cursorline` in config and it works in other themes. I guess the issue is in the color theme.

**Comment by AlphaTechnolog** [comment]
I'll check this later, but I could miss some highlight lol thank u :3

**Comment by AlphaTechnolog** [comment]
i don't really know what color i can use, because pywal don't generate for me a color that looks sick for the cursorline (like a contrastbg) :/ so i don't really know how can i implement this, closing for now....

a possible solution is calc the color using the bg color (but i need to make that functions in lua, and to implement this i will need time)
